In [1]:
import numpy as np
import pandas as pd

In [2]:
data =pd.DataFrame({'text':['people watch campusx','campusx watch campusx','pepole write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
data

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   pepole write comment       0
3  campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(data['text'])

In [6]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 4, 'campusx': 0, 'pepole': 3, 'write': 5, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 0 1 0]]
[[2 0 0 0 1 0]]


In [8]:
cv.transform(['campusx watch and write comment of compusx']).toarray()

array([[1, 1, 0, 0, 1, 1]])

# N-grams

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [10]:
bow = cv.fit_transform(data['text'])


In [11]:
# vocab
print(cv.vocabulary_)

{'people': 6, 'watch': 12, 'campusx': 0, 'people watch': 7, 'watch campusx': 13, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'pepole': 9, 'write': 14, 'comment': 5, 'pepole write': 10, 'write comment': 15, 'pepole write comment': 11, 'campusx write': 3, 'campusx write comment': 4}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0]]


In [13]:
cv = CountVectorizer(ngram_range=(2,2))

In [14]:
bow = cv.fit_transform(data['text'])

In [15]:
# vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'pepole write': 3, 'write comment': 5, 'campusx write': 1}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [17]:
cv = CountVectorizer(ngram_range=(3,3))

In [18]:
bow = cv.fit_transform(data['text'])

In [19]:
# vocab
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'pepole write comment': 3, 'campusx write comment': 1}


In [20]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0]]
[[1 0 0 0]]


In [21]:
#calculate length

In [22]:
cv = CountVectorizer(ngram_range=(1,3))

In [23]:
bow = cv.fit_transform(data['text'])

In [24]:
# vocab
print(len(cv.vocabulary_))

16


In [25]:
data

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   pepole write comment       0
3  campusx write comment       0

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(data['text']).toarray()

array([[0.44809973, 0.        , 0.70203482, 0.        , 0.55349232,
        0.        ],
       [0.8508161 , 0.        , 0.        , 0.        , 0.52546357,
        0.        ],
       [0.        , 0.52640543, 0.        , 0.66767854, 0.        ,
        0.52640543],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.        ,
        0.61366674]])

In [27]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.91629073 1.91629073 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'pepole' 'watch' 'write']
